repos:
  - repo: local
    hooks:
      - id: pre-commit-script
        name: pre-commit-script
        entry: .pre-commit-script.sh
        language: script
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        - id: check-yaml
          always_run: true
