---
- import_tasks: download.yml
  vars:
    ansible_become: false

# run app command
- name: run app_ctrl cmd
  become: "{{ user is defined }}"
  become_user: "{{ user | default(None) }}"
  shell: "{{ cmd }}"
  register: app_ctrl_cmd

- debug:
    msg: "{{ app_ctrl_cmd }}"
  when: log|default(false)

# wait for pid or no_pid ( 2 min in total )
- name: get pid
  changed_when: "false"
  become: "false"
  shell: 'GREP_PATTERN="^$CMD_USER[ ]+([0-9]+)[ ]+(.*)$"; 
          ps -e -o user:50,pid:20,cmd:50 | more | grep -oP "$GREP_PATTERN"  | sed -r "s/$GREP_PATTERN/\1-\2/" | grep -E "^[0-9]+-$PROCESS_SEARCH_PATTERN" | sed -r "s/^([0-9]+)-.*$/\1/"'
  environment:
    CMD_USER: "{{ process_user|default('.+') }}"
    PROCESS_SEARCH_PATTERN: "{{ process_regex }}"
  register: get_pid_out
  delay: 10
  retries: 12
  until:
    - ( get_pid_out.stdout=='' and wait_until|default('')=='no_pid' ) or ( get_pid_out.stdout!='' and wait_until|default('')=='pid' )
  when: wait_until|default('')=='no_pid' or wait_until|default('')=='pid'
