---
- import_tasks: download.yml
  vars:
    ansible_become: false

- name: test
  debug:
    msg: "test"

#user: tomcat
#cmd: "sudo systemctl stop tomcat"
#process_regex: "/.*/java/current/bin/java.*/.*/tomcat/.*"
#wait_until: no_pid

# run app command
- name: run app_ctrl cmd
  become: "{{ user is defined }}"
  become_user: "{{ user | default(None) }}"
  changed_when: "changed_when|default(true)"
  shell: "{{ cmd }}"


# wait for pid or no_pid ( 2 min in total )
- name: get pid
  changed_when: "false"
  shell: 'GREP_PATTERN="^$CMD_USER[ ]+([0-9]+)[ ]+([0-9]+)[ ]+[0-9]+[ ]+[0-9A-Za-z:]+[ ]+[^ ]+[ ]+[0-9\:-]+[ ]+(.*)$"; 
          ps -Af | grep -oP "$GREP_PATTERN"  | sed -r "s/$GREP_PATTERN/\1-\3/" | grep -E "^[0-9]+-$PROCESS_SEARCH_PATTERN" | sed -r "s/^([0-9]+)-.*$/\1/"'
  environment:
    CMD_USER: "{{ process_user|default('.+') }}"
    PROCESS_SEARCH_PATTERN: "{{ process_regex }}"
  register: get_pid_out
  delay: 10
  retries: 12
  until:
    - ( get_pid_out.stdout=='' and wait_until|default('')=='no_pid' ) or ( get_pid_out.stdout!='' and wait_until|default('')=='pid' )
  when: wait_until|default('')=='no_pid' or wait_until|default('')=='pid'

- debug:
    msg: "{{get_pid_out}}"
