---
- name: Make sure destination dirs exists
  become_user: "{{ item.owner }}"
  file:
    path: "{{ item.dest | dirname }}"
    state: directory
  with_items: |
    {{ 
      root_files     | default([]) | union( 
      root_templates | default([]) 
      ) 
    }}

- name: deploy root_files
  become_user: "{{ item.owner }}"
  copy:
    src:    "{{ item.src }}"
    dest:   "{{ item.dest }}"
    owner:  "{{ item.owner }}"
    group:  "{{ item.group }}"
    mode:   "{{ item.mode }}"
  with_items: "{{ root_files | default([]) }}"

- name: deploy root_templates
  become_user: "{{ item.owner }}"
  template:
    src:    "{{ item.src }}"
    dest:   "{{ item.dest }}"
    owner:  "{{ item.owner }}"
    group:  "{{ item.group }}"
    mode:   "{{ item.mode }}"
  with_items: "{{ root_templates | default([]) }}"
