FROM docker.io/ubuntu:latest
RUN apt-get update

RUN apt install -y ssh wget curl bash ansible sshpass zip unzip git

ENV ANSIBLE_CONFIG=.docker/ansible.cfg
ENV ANSIBLE_DEBUG=0
ENV ANSIBLE_FORCE_COLOR=True
